const ProductosFerreteria = [
  {
    codigo: 0001,
    nombre: "Martillo",
    precio: 20000,
    cantidad_disponible: 300,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0002,
    nombre: "Alicate",
    precio: 31000,
    cantidad_disponible: 350,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0003,
    nombre: "Destornillador",
    precio: 12200,
    cantidad_disponible: 200,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0004,
    nombre: "LLave inglesa",
    precio: 40000,
    cantidad_disponible: 200,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0005,
    nombre: "Cinta metrica",
    precio: 20000,
    cantidad_disponible: 400,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0006,
    nombre: "Nivel",
    precio: 25000,
    cantidad_disponible: 200,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0007,
    nombre: "Serrucho",
    precio: 24000,
    cantidad_disponible: 150,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0010,
    nombre: "Taladro manual",
    precio: 289000,
    cantidad_disponible: 100,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0011,
    nombre: "Llave fija",
    precio: 40000,
    cantidad_disponible: 200,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0012,
    nombre: "Llave ajustable",
    precio: 50000,
    cantidad_disponible: 150,
    tipo: "Manual",
    imagen: "",
  },
  {
    codigo: 0013,
    nombre: "Clavos",
    precio: 4000,
    cantidad_disponible: 300,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0014,
    nombre: "Tornillos",
    precio: 2000,
    cantidad_disponible: 200,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0015,
    nombre: "Tuercas",
    precio: 15200,
    cantidad_disponible: 400,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0016,
    nombre: "Tarugos",
    precio: 60000,
    cantidad_disponible: 100,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0017,
    nombre: "Pernos",
    precio: 20000,
    cantidad_disponible: 150,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0020,
    nombre: "Grapas",
    precio: 15000,
    cantidad_disponible: 300,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0021,
    nombre: "Bisagras",
    precio: 500,
    cantidad_disponible: 300,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0022,
    nombre: "Ganchos",
    precio: 10000,
    cantidad_disponible: 75,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0023,
    nombre: "Ventosas",
    precio: 20000,
    cantidad_disponible: 100,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0024,
    nombre: "Anclajes",
    precio: 700,
    cantidad_disponible: 40,
    tipo: "Fijacion",
    imagen: "",
  },
  {
    codigo: 0025,
    nombre: "Cemento",
    precio: 32000,
    cantidad_disponible: 50,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0026,
    nombre: "Arena",
    precio: 40000,
    cantidad_disponible: 20,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0027,
    nombre: "Pintura",
    precio: 45000,
    cantidad_disponible: 60,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0030,
    nombre: "Yeso",
    precio: 30000,
    cantidad_disponible: 79,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0031,
    nombre: "Ladrillos",
    precio: 1000,
    cantidad_disponible: 1000,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0032,
    nombre: "Baldosas",
    precio: 150000,
    cantidad_disponible: 700,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0033,
    nombre: "Tejas",
    precio: 3000,
    cantidad_disponible: 400,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0034,
    nombre: "Caños",
    precio: 60000,
    cantidad_disponible: 35,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0035,
    nombre: "Alambre",
    precio: 5000,
    cantidad_disponible: 700,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0036,
    nombre: "Tubos",
    precio: 20000,
    cantidad_disponible: 600,
    tipo: "Construccion",
    imagen: "",
  },
  {
    codigo: 0037,
    nombre: "Bombillas",
    precio: 5000,
    cantidad_disponible: 600,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0040,
    nombre: "Interruptores",
    precio: 4000,
    cantidad_disponible: 300,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0041,
    nombre: "Tomacorrientes",
    precio: 5000,
    cantidad_disponible: 200,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0042,
    nombre: "Cables",
    precio: 20000,
    cantidad_disponible: 6000,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0043,
    nombre: "Cinta aislante",
    precio: 3500,
    cantidad_disponible: 400,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0044,
    nombre: "Fusibles",
    precio: 200,
    cantidad_disponible: 44,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0045,
    nombre: "Extension",
    precio: 12000,
    cantidad_disponible: 500,
    tipo: "Electricidad",
    imagen: "",
  },
  {
    codigo: 0046,
    nombre: "Pala",
    precio: 35000,
    cantidad_disponible: 200,
    tipo: "Jardineria",
    imagen: "",
  },
  {
    codigo: 0047,
    nombre: "Rastrillo",
    precio: 40000,
    cantidad_disponible: 600,
    tipo: "Jardineria",
    imagen: "",
  },
  {
    codigo: 0050,
    nombre: "Manguera",
    precio: 60000,
    cantidad_disponible: 150,
    tipo: "Jardineria",
    imagen: "",
  },
];
